/********************************************************************
 *  Copyright 2025 Adobe
 *  All Rights Reserved.
 *
 * NOTICE:  Adobe permits you to use, modify, and distribute this
 * file in accordance with the terms of the Adobe license agreement
 * accompanying it.
 *******************************************************************/
declare const Facet = "\n  fragment Facet on Aggregation {\n    title\n    attribute\n    buckets {\n      title\n      __typename\n      ... on CategoryView {\n        name\n        count\n        path\n      }\n      ... on ScalarBucket {\n        count\n      }\n      ... on RangeBucket {\n        from\n        to\n        count\n      }\n      ... on StatsBucket {\n        min\n        max\n      }\n    }\n  }\n";
declare const ProductView = "\n  fragment ProductView on ProductSearchItem {\n    productView {\n      __typename\n      sku\n      name\n      inStock\n      url\n      urlKey\n      images {\n        label\n        url\n        roles\n      }\n      ... on ComplexProductView {\n        priceRange {\n          maximum {\n            final {\n              amount {\n                value\n                currency\n              }\n            }\n            regular {\n              amount {\n                value\n                currency\n              }\n            }\n          }\n          minimum {\n            final {\n              amount {\n                value\n                currency\n              }\n            }\n            regular {\n              amount {\n                value\n                currency\n              }\n            }\n          }\n        }\n        options {\n          id\n          title\n          values {\n            title\n            ... on ProductViewOptionValueSwatch {\n              id\n              inStock\n              type\n              value\n            }\n          }\n        }\n      }\n      ... on SimpleProductView {\n        price {\n          final {\n            amount {\n              value\n              currency\n            }\n          }\n          regular {\n            amount {\n              value\n              currency\n            }\n          }\n        }\n      }\n    }\n    highlights {\n      attribute\n      value\n      matched_words\n    }\n  }\n";
export { Facet, ProductView };
//# sourceMappingURL=fragments.graphql.d.ts.map