/*! Copyright 2025 Adobe
All Rights Reserved. */
import{T as u}from"./subscription-email-statuses.js";import"@dropins/tools/lib.js";import{events as C}from"@dropins/tools/event-bus.js";import{signal as m,computed as w}from"@dropins/tools/signals.js";import{FetchGraphQL as q}from"@dropins/tools/fetch-graphql.js";var U=(e=>(e.CartUpdate="cartUpdate",e.Default="default",e.ShippingEstimate="shippingEstimate",e))(U||{});const p=new Map,g=new Map,i=m(new Set),y=new Map;y.set("cartUpdate",e=>{C.emit("checkout/updated",e)});async function v(e){g.set(e,!0);const t=p.get(e);let s;for(;t.length>0;){const o=t.shift();try{const a=await o.requestFn();o.resolve(a),s=a}catch(a){o.reject(a)}}g.set(e,!1);const r=new Set(i.value);r.delete(e),i.value=r;const n=y.get(e);n&&s&&n(s)}function A(e,t="default"){p.has(t)||p.set(t,[]);const s=p.get(t),r=new Promise((o,a)=>{s.push({requestFn:e,resolve:o,reject:a})}),n=new Set(i.value);return n.add(t),i.value=n,g.get(t)||v(t),r}const B=w(()=>i.value.has("cartUpdate")),H=w(()=>i.value.has("shippingEstimate")),D=["sender_email","recipient_email"];function T(e){return e.filter(t=>!t.path||!D.some(s=>{var r;return((r=t.path)==null?void 0:r.at(-1))===s}))}const x=e=>{throw e instanceof DOMException&&e.name==="AbortError"||C.emit("error",{source:"checkout",type:"network",error:e}),e};function b(e,t){return t.split(".").reduce((s,r)=>s&&s[r]!==void 0?s[r]:void 0,e)}async function G(e){const{defaultValueOnFail:t,options:s,path:r,query:n,queueName:o,transformer:a,type:d}=e;try{const l=async()=>{const{data:S,errors:E}=await k(n,{method:d==="query"?"GET":"POST",cache:d==="query"?"no-cache":void 0,...s}).catch(x);if(E){const _=T(E);if(_.length>0)throw new L(_)}let h=b(S,r);if(h===void 0)throw new Error(`No data found at path: ${r}`);return a?a(h):h};return d==="mutation"?await A(l,o):await l()}catch(l){if(t!==void 0)return t;throw l}}const F=`
  query getStoreConfig {
    storeConfig {
      default_country
      is_checkout_agreements_enabled
      is_guest_checkout_enabled
      is_one_page_checkout_enabled
      newsletter_enabled
      shopping_cart_display_shipping
    }
  }
`,I="US",f={defaultCountry:I,agreementsEnabled:!0,newsletterEnabled:!0,shoppingCartDisplaySetting:{shipping:u.EXCLUDING_TAX}},V=async()=>await G({defaultValueOnFail:f,options:{method:"GET",cache:"no-cache"},path:"storeConfig",query:F,transformer:N,type:"query"});function M(e){switch(e){case 1:return u.EXCLUDING_TAX;case 2:return u.INCLUDING_TAX;case 3:return u.INCLUDING_EXCLUDING_TAX;default:return u.EXCLUDING_TAX}}function N(e){if(!e)return f;const{default_country:t,is_checkout_agreements_enabled:s,newsletter_enabled:r,shopping_cart_display_shipping:n}=e;return{defaultCountry:t||f.defaultCountry,agreementsEnabled:s,newsletterEnabled:r,shoppingCartDisplaySetting:{shipping:M(n)}}}const Y=m(),{setEndpoint:$,setFetchGraphQlHeader:z,removeFetchGraphQlHeader:J,setFetchGraphQlHeaders:K,fetchGraphQl:k,getConfig:W}=new q().getMethods();class L extends Error{constructor(t){super(t.map(s=>s.message).join(" ")),this.name="FetchError"}}class c extends Error{constructor(t){super(t),this.name="InvalidArgument"}}class Z extends Error{constructor(t){super(t),this.name="UnexpectedError"}}class ee extends c{constructor(){super("Cart ID is required")}}class te extends c{constructor(){super("Email is required")}}class se extends c{constructor(){super("Payment method code is required")}}class re extends c{constructor(){super("Shipping address is required")}}class ne extends c{constructor(){super("Billing address is required")}}class ae extends c{constructor(){super("Country Code is required")}}const oe=m(!0);export{I as D,L as F,c as I,ee as M,U as Q,f as S,Z as U,H as a,ae as b,re as c,G as d,te as e,$ as f,z as g,B as h,oe as i,K as j,k,W as l,V as m,se as n,ne as o,J as r,Y as s};
