name: Cypress E2E SaaS Tests
on: push
jobs:
  cypress-saas-run:
    # If you want this job to run on your fork, remove the below "if" line.
    # You will need to "fix" the tests as they are specific to Adobe Commmerce's
    # demo backend.
    if: github.repository == 'hlxsites/aem-boilerplate-commerce'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install root dependencies
        run: npm ci
      - name: Install adobe aem cli dependencies
        run: npm install -g @adobe/aem-cli
      - name: Start server in the background
        run: aem up --url https://main--boilerplate-accs--adobe-commerce.aem.live/ &
      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: cypress
          wait-on: 'http://localhost:3000'
          command: npm run cypress:saas:run
        env:
          AEM_ASSETS_PRIVATE_USER: ${{ secrets.AEM_ASSETS_PRIVATE_USER }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
